apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  selector:
    matchLabels:
      service: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: toqamo/udagram-api-user:latest
        name: backend-user
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2024Mi"
            cpu: "500m"
        env:
        - name: URL
          value: "http://localhost:8100"
        - name: JWT_SECRET
          value: "hello"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_HOST
          value: "cdr.cyp0zvvuwdsg.us-east-1.rds.amazonaws.com"
        - name: POSTGRES_PASSWORD
          value: "toqamuhammad25"
        - name: POSTGRES_USERNAME
          value: "toqa"
      restartPolicy: Always


